name: tests

on:
  pull_request:
  schedule:
    - cron: '0 12 * * 0'  # run once a week on Sunday
  # Allow to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    strategy:
      # We want to see all failures:
      fail-fast: false
      matrix:
        os:
        - ["ubuntu", "ubuntu-24.04"]
        config:
        # [Python version, tox env]
        - ["3.10",  "py310"]
        - ["3.11",  "py311"]
        - ["3.12",  "py312"]
        - ["3.13",  "py313"]
        - ["3.14",  "py314"]

    runs-on: ${{ matrix.os[1] }}
    name: ${{ matrix.config[1] }}
    steps:
    - uses: actions/checkout@v6

    - name: Install uv and Python ${{ matrix.config[0] }}
      uses: astral-sh/setup-uv@v7
      with:
        # Install a specific version of uv.
        version: "0.9.26"
        python-version: ${{ matrix.config[0] }}

    - name: Install tox
      run: uv tool install tox --with tox-uv

    - name: Test
      run: tox r -e ${{ matrix.config[1] }}
